---
- name: Create Infrastructure
  cloudformation:
    stack_name: "{{ stack_name }}"
    state: "present"
    region: "{{ region }}"
    template: "../roles/cloudformation-infra/files/infrastructure.template"
    template_parameters:
      Region: "{{ region }}"
      Route53HostedZone: "{{ public_hosted_zone }}."
      PublicHostedZone: "{{ public_hosted_zone }}"
      VpcCidrBlock: "{{ cidr_block }}"
      VpcName: "{{ vpc_prefix }}"
      SubnetCidrBlocks: "{{ subnet_blocks }}"
      KeyName: "{{ keypair }}"
      AmiId: "{{ ami }}"
      BastionInstanceType: "{{ bastion_instance_type }}"
      BastionUserData: "{{ lookup('file', 'user_data_bastion.yaml') | b64encode }}"
    tags:
      AWSAnsible: "{{ stack_name }}"
  when: create_vpc == "yes"
